(()=>{const D=window.MADRASA_DATA,C=D.columns,R=D.rows,dict=D.dicts,ix=Object.fromEntries(C.map((c,i)=>[c,i]));const v=(c,n)=>dict[c][n],$=x=>document.getElementById(x);let state={rows:R,page:1,size:25};$("total").textContent=R.length.toLocaleString("bn-BD");$("heroCount").textContent=R.length.toLocaleString("bn-BD");
function unique(c){return [...new Set(R.map(r=>v(c,r[ix[c]])))].sort((a,b)=>a.localeCompare(b))}
function fill(id,c){unique(c).forEach(x=>{let o=document.createElement("option");o.value=x;o.textContent=x;$(id).append(o)})}
fill("division","DIVISION");fill("district","DISTRICT");fill("upazila","UPAZILLA/THANA");fill("level","LAVEL");fill("post","POST-NAME");fill("subject","SUBJECT");
function apply(){let q=$("q").value.trim().toLowerCase(),fs={"DIVISION":$("division").value,"DISTRICT":$("district").value,"UPAZILLA/THANA":$("upazila").value,"LAVEL":$("level").value,"POST-NAME":$("post").value,"SUBJECT":$("subject").value};
state.rows=R.filter(r=>{if(q){let h=[r[ix.EIIN],...Object.keys(fs).map(c=>v(c,r[ix[c]]))].join(" ").toLowerCase();if(!h.includes(q))return false}return Object.entries(fs).every(([c,x])=>!x||v(c,r[ix[c]])===x)});state.page=1;render()}
function render(){let a=state.rows,s=state.size,p=Math.max(1,Math.ceil(a.length/s));state.page=Math.min(state.page,p);let st=(state.page-1)*s,en=Math.min(st+s,a.length);$("result").textContent=a.length.toLocaleString("bn-BD");$("districts").textContent=new Set(a.map(r=>v("DISTRICT",r[ix.DISTRICT]))).size.toLocaleString("bn-BD");$("madrasas").textContent=new Set(a.map(r=>v("MADRASHA-NAME",r[ix["MADRASHA-NAME"]]))).size.toLocaleString("bn-BD");$("range").textContent=a.length?`(${(st+1).toLocaleString("bn-BD")}–${en.toLocaleString("bn-BD")})`:"";$("page").textContent=`পৃষ্ঠা ${state.page.toLocaleString("bn-BD")} / ${p.toLocaleString("bn-BD")}`;$("prev").disabled=state.page<=1;$("next").disabled=state.page>=p;let tb=$("tbody");tb.innerHTML="";for(let i=st;i<en;i++){let r=a[i],tr=document.createElement("tr");["SL","EIIN","MADRASHA-NAME","LAVEL","POST-NAME","SUBJECT","DIVISION","DISTRICT","UPAZILLA/THANA"].forEach((c,j)=>{let td=document.createElement("td");td.textContent=j<2?r[ix[c]]:v(c,r[ix[c]]);tr.append(td)});tb.append(tr)}}
function bars(id,c,n=8){let counts={};state.rows.forEach(r=>{let x=v(c,r[ix[c]]);counts[x]=(counts[x]||0)+1});let top=Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,n),max=top[0]?.[1]||1;$(id).innerHTML=top.map(([k,n])=>`<div class="bar"><div class="barline"><span>${k}</span><b>${n.toLocaleString("bn-BD")}</b></div><div class="track"><div class="fill" style="width:${n/max*100}%"></div></div></div>`).join("")}
function dashboard(){bars("districtBars","DISTRICT",8);bars("divisionBars","DIVISION",8);bars("subjectBars","SUBJECT",8)}
["q","division","district","upazila","level","post","subject"].forEach(id=>$(id).addEventListener(id==="q"?"input":"change",()=>{apply();dashboard()}));
$("size").onchange=()=>{state.size=+$("size").value;state.page=1;render()};$("prev").onclick=()=>{state.page--;render()};$("next").onclick=()=>{state.page++;render()};
$("reset").onclick=()=>{["q","division","district","upazila","level","post","subject"].forEach(id=>$(id).value="");apply();dashboard()};dashboard();render()})()